### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by TheFox** [humhub/polls#106]
What is the minimum required PHP version for this module? I saw some of the code is probably PHP 7, but I am not sure. Are there any plans for migrating it to PHP 7 and further to PHP 8?

For example the old array syntax using `array()` is used instead of the new `[]`.

Also the fully qualified class name is used as a string instead of `::class`.

**Comment by luke-** [comment]
We test it against 7.4

**Comment by TheFox** [comment]
How can I know? How do you know? There is no composer.json or something.

**Comment by luke-** [comment]
You can see here with which HumHub version the module is compatible.
https://github.com/humhub/polls/blob/master/module.json#L8

The requirements for the modules are the same as for the respective HumHub version.

**Comment by TheFox** [comment]
@luke- But the website https://docs.humhub.org/docs/admin/requirements#php-environment says we can you PHP 8.1 ? So what's right here?

Why are some of the `Yes` in bold and some not?

**Comment by TheFox** [comment]
But you wrote

> We test it against 7.4

So you also testing against 8.0 and 8.1 ?
