### ISSUE TITLE
No way to create a poll outside spaces.

### ISSUE THREAD

**Issue by AkashicSeer** [humhub/polls#112]
I've been experimenting with Humhub. I was excited to see it has a polls module, which I installed and activated.  It appears that polls are only possible in Spaces. Is this true? Is there any future plan to allow for the creation of polls in regular user posts? I assumed that was what polls were for, but they only show up in spaces.

**Comment by felixhahnweilheim** [comment]
You have to activate the polls module for your profile. Account settings -> Modules

**Comment by AkashicSeer** [comment]
So every single person needs to do this? I figured it was controlled by the
administrator. That is confusing. Thanks.

**Comment by felixhahnweilheim** [comment]
As I added to my comment above the admin can set it as default.

**Comment by AkashicSeer** [comment]
Ok, thanks.
