### ISSUE TITLE
Scheduled content

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/polls#119]
Support the scheduled content feature implemented here https://github.com/humhub/team_tasks/issues/274.

**Comment by yurabakhtin** [comment]
@luke- I think it is nothing to do for this module because a Poll is created throught wall stream form, so all functionality already works as expected:

![poll-scheduled](https://user-images.githubusercontent.com/6995524/220893818-c449c6f8-4366-4763-b7cb-9200c4aec439.png)

**Comment by luke-** [comment]
Very good, that's how it should be :-)
