### ISSUE TITLE
polls no more visible in Space-Menue

### ISSUE THREAD

**Issue by JuergenEl** [humhub/polls#120]
self-hosted Installation. Original humhub-theme. humhub-Version: 1.13.1 
Since a few days (without changing anything manually) polls are no more visible in any Space-Menue.
Old Polls could be edited and shown via link/stream. But no possiblity to generate new Polls.
Any Idear?

**Comment by luke-** [comment]
It's now included in the post form 
![image](https://user-images.githubusercontent.com/4736168/222123239-661ddbce-b085-4ecd-b454-eb61913518de.png)

with HumHub 1.14 we're always display the tabs

**Comment by JuergenEl** [comment]
oh, oh ... did not seen that - thank you very much indeed for quick answering :-)
