### ISSUE TITLE
Missing Translation for Vote Pluralization String in pt-BR Translation File

### ISSUE THREAD

**Issue by Dheyvidj** [humhub/polls#139]
In the pt-BR translation file for the polls module, there is a missing translation for the key related to the vote count with pluralization. The key `` {n,plural,=1{# {htmlTagBegin}vote{htmlTagEnd}}other{# {htmlTagBegin}votes{htmlTagEnd}}} `` is present, but the corresponding translation value is empty. This results in the incorrect display of the translated text for vote counts and formatting. The appropriate translation needs to be added to ensure consistent interface language for pt-BR users.

**Comment by Dheyvidj** [comment]
The correct value for the translation of the key in the pt-BR translation file should be 
`` {n,plural,=1{# {htmlTagBegin}voto{htmlTagEnd}}other{# {htmlTagBegin}votos{htmlTagEnd}}} `` 
This will ensure that the vote count is displayed correctly in Portuguese, adhering to the rules of pluralization.

**Comment by yurabakhtin** [comment]
@Dheyvidj @luke- PR https://github.com/humhub/polls/pull/140:

![votes](https://github.com/user-attachments/assets/90943ad4-b2c7-48e2-80ac-ec007c4b04bf)
