### ISSUE TITLE
Not work in branch v1.2-dev

### ISSUE THREAD

**Issue by alvis1981** [humhub/polls#26]
Hello.
The module does not work in the branch v1.2-dev.
This is due to removal of Wall.
Tell me what to do so that the module has earned.

**Comment by buddha87** [comment]
The v1.2 dev branch is an unstable developer branch and should not be used until you want to contribute to this version. There are several modules not compatible with this version.

**Comment by alvis1981** [comment]
Probably will roll back this audit 12bd2b28e1a882164a243388caf4c494b8bc277a, so that the module became operational.
Did you advise to make other changes, replace the use of the essence of wall on anything else?
