### ISSUE TITLE
Poll email notification has wrong entry?id

### ISSUE THREAD

**Issue by wellsite** [humhub/polls#37]
When a new poll is created Humhub is sending email notifications to users containing "View online" links with the wrong entry?id, resulting in the following error message.

Oooops... It looks like you may have taken the wrong turn.
The requested content is not valid or was removed!

**Comment by wellsite** [comment]
User creating poll also receives this error message:

{
    "url": "/humhub/s/welcome-space/polls/poll/create",
    "status": 503,
    "response": "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n<p>Additionally, a 503 Service Unavailable\nerror was encountered while trying to use an ErrorDocument to handle the request.</p>\n</body></html>\n",
    "textStatus": "error",
    "dataType": "json",
    "xhr": {
        "readyState": 4,
        "responseText": "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n<p>Additionally, a 503 Service Unavailable\nerror was encountered while trying to use an ErrorDocument to handle the request.</p>\n</body></html>\n",
        "status": 503,
        "statusText": "Service Unavailable"
    },
    "json": "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n<p>Additionally, a 503 Service Unavailable\nerror was encountered while trying to use an ErrorDocument to handle the request.</p>\n</body></html>\n",
    "error": {},
    "errorThrown": "Service Unavailable",
    "validationError": false
}

**Comment by buddh4** [comment]
Could not reproduce this issue. The `The requested content is not valid or was removed!` is often displayed, if you try to open a notification of another user. Perhaps you were logged in with the author of the question and clicked on the notification, then you'd see this message.

I also could not recreate the service unavailable error, I could create the polls just fine. Probably rather a server issue, perhaps a .htaccess issue.
