### ISSUE TITLE
[Feature Request] Add RichTextField layout

### ISSUE THREAD

**Issue by ArchBlood** [humhub/polls#73]
I believe it would be easier to also add the layout of the richtext field within the `form.php` & `edit.php` files or at least make it an optional configuration

### form.php
```php
<?= RichTextField::widget([
        'name' => 'Poll[question]',
        'layout' => RichTextField::LAYOUT_INLINE,
        'placeholder' => Yii::t('PollsModule.widgets_views_pollForm', "Ask something...")
]); ?>
```
or

```php
<?= RichTextField::widget([
        'name' => 'Poll[question]',
        'layout' => RichTextField::LAYOUT_BLOCK,
        'placeholder' => Yii::t('PollsModule.widgets_views_pollForm', "Ask something...")
]); ?>
```

### edit.php
```php
<?= $form->field($poll, 'question')->widget(RichTextField::class, ['layout' => RichTextField::LAYOUT_INLINE, 'disabled' => $poll->closed, 'placeholder' => Yii::t('PollsModule.widgets_views_pollForm', 'Edit your poll question...')]) ?>
```
or
```php
<?= $form->field($poll, 'question')->widget(RichTextField::class, ['layout' => RichTextField::LAYOUT_BLOCK, 'disabled' => $poll->closed, 'placeholder' => Yii::t('PollsModule.widgets_views_pollForm', 'Edit your poll question...')]) ?>
```

**Comment by buddh4** [comment]
In an upcoming version there will be seperated question and description field. I think in this case the block layout is totally fine. I also think its not a problem in the current form. Is there a reason you prefer the inline layout here?

**Comment by ArchBlood** [comment]
It looks better on mobile view with the layout applied and doesn't seem all bulky as it does now

**Comment by buddh4** [comment]
When focused its as bulky as this? I think we should rather try to generally improve mobile usability of the richtext.

**Comment by ArchBlood** [comment]
I believe that default is set to `LAYOUT_BLOCK`? Here in lies the problem for some newer devices (e.g. Samsung Galaxy A10e my current device version which isn't much newer now) the screen is rather small width wise so this makes the Richtext editor look and feel bulky where's when using `LAYOUT_INLINE` it isn't bulky and gives everything one would expect to use :thinking:

**Comment by buddh4** [comment]
But what is less bulky on the inline editor, just the show more plugin icon to collapse/extend the menu? The icons etc should be the same size.

**Comment by ArchBlood** [comment]
`LAYOUT_BLOCK` gives no options to extend/collapse the Richtext menu, would be nice if it did but on extending the menu it would still be rather bulky compared to `LAYOUT_INLINE` from what tests were done comparing between the two in Green Meteor and the HumHub community site :thinking:

**Comment by buddh4** [comment]
k, but then its a general issue with the mobile usability of the block layout, we won't change all richtexts to the inline layout, so we have to think about how to improve the mobile usability of this layout. I think the inline layout is rather a bit hacky with the overlay style. For example in the wiki its probably the same problem.
