### ISSUE TITLE
Poll notifications not working

### ISSUE THREAD

**Issue by JK742020** [humhub/polls#75]
It seems that notifications are not working within the poll module.

I activated the notifications for the space where I created and published the poll and I checked if notifications is activated for the certain poll. Both things ok.

I can’t see any possibility to change settings for polls in the admin area. So no idea how to get it working.

I’d like to see when people made theire choice and stay informed about the development of the poll.

**Comment by buddh4** [comment]
There currently are no poll specific notifications. Currently there is only an activity. In bigger networks a notification on every vote is probably a bit too much, so this should at least be configurable. I think a notification if a poll was closed or reopened would also be great.

**Comment by JK742020** [comment]
Yes in bigger networks it would be too much to get a notification every time somebody was voting. In my case it would be really good. So let's make notifications optional. Maybe also put it into the administration/notifications area.
One more question: I can enable/disable notifications within every poll. What are the notifications I enable/disable for?

**Comment by buddh4** [comment]
@JK742020 do you mean this:

![grafik](https://user-images.githubusercontent.com/9800854/96475019-ce609400-1233-11eb-9e38-db29c7e4bfb2.png)

This is available on all types of content and will enable/disable notifications e.g. when someone comments on this content.

- The author of a content is automatically subscribed to a content
- When commenting a content, you'll be automatically subscribed
- Users who are interested in the conversation, but did not comment yet, can manually subscribe to this content
- Users who do not want to receive notifications for a content can manually unsubscribe
- When creating a post, the author can add users who should be subscribed:

![grafik](https://user-images.githubusercontent.com/9800854/96475424-4dee6300-1234-11eb-9cef-bbdc79a43147.png)

**Comment by JK742020** [comment]
Thanks for the details!
Something has been new for me and it's good to know that. This means the notifications within poll is for the comments, right?
Still it would be great to have the possibility to get notified when a choice is made. But if it's just me asking for that feature I can really go with the way it is.

One last question. If I select notifications on the Space-Level by selecting this underneath the space-picture this means I'm subscribed to all posts which will come in the future. Right?

Thanks!

**Comment by buddh4** [comment]
When you activate `Receive Notifications for new content` you will receive notifications if any new content was created, but you won't be subscribed to the content automatically (receive notifications for new comments).

**Comment by JK742020** [comment]
ok got it. Thanks.
